using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace GladLive.Security.RSAGen.Lib
{
	/// <summary>
	/// Abstracts loading semantics for an ".rsa" keyfile generated by <see cref="GladLive.Security.RSAGen.App"/>.
	/// </summary>
	public class RSAKeyLoader
	{
		/// <summary>
		/// <see cref="RSACryptoServiceProvider"/> generated from the loaded ".rsa" keypair file.
		/// </summary>
		public RSACryptoServiceProvider Provider { get; }

		public RSAKeyLoader(string rsaKeyFilePath)
		{
			//Simply creates a new RSA provider and loads the XML string.
			Provider = new RSACryptoServiceProvider();
			Provider.FromXmlString(File.ReadAllText(rsaKeyFilePath));
		}
	}
}
